name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99
    
    container: 
      image: spector3702/neat-parallel:latest
      options: --privileged  # This is required for Docker-in-Docker capabilities

    steps:
    - uses: actions/checkout@v2

    - name: Prepare and test DDPG
      run: |
        chmod +x TORCS_DDPG/CI_DDPG.sh
        TORCS_DDPG/CI_DDPG.sh

    - name: Prepare and test NEAT
      run: |
        chmod +x TORCS_NEAT/CI_NEAT.sh
        TORCS_NEAT/CI_NEAT.sh

    - name: Run parallel NEAT
      run: |
        export HOST_PATH=$PWD  # Set the HOST_PATH environment variable for your script
        python TORCS_NEAT/train_parallel.py --generations 1
