name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull Docker image
      run: docker pull spector3702/neat-parallel:latest

    - name: Run and test DDPG within Docker container
      run: |
        docker run --rm \
        -v $PWD:/TorcsBot \
        spector3702/neat-parallel:latest \
        bash -c "chmod +x TORCS_DDPG/CI_DDPG.sh && TORCS_DDPG/CI_DDPG.sh"

    - name: Run and test NEAT within Docker container
      run: |
        docker run --rm \
        -v $PWD:/TorcsBot \
        spector3702/neat-parallel:latest \
        bash -c "chmod +x TORCS_NEAT/CI_NEAT.sh && TORCS_NEAT/CI_NEAT.sh"

    - name: Run parallel NEAT within Docker container
      run: |
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $PWD:/TorcsBot \
        -e HOST_PATH=$PWD \
        spector3702/neat-parallel:latest \
        python TORCS_NEAT/train_parallel.py --generations 1
