name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull Docker image
      run: docker pull spector3702/neat-parallel:latest

    - name: Run and test DDPG within Docker container
      run: |
        docker run --rm -v $PWD:/TorcsBot spector3702/neat-parallel:latest bash -c "chmod +x TORCS_NEAT/bashes/* && TORCS_NEAT/bashes/CI_DDPG.sh"

    - name: Run and test NEAT within Docker container
      run: |
        docker run --rm -v $PWD:/TorcsBot spector3702/neat-parallel:latest bash -c "chmod +x TORCS_NEAT/bashes/* && TORCS_NEAT/bashes/CI_NEAT.sh"
