name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    container: 
      image: spector3702/neat-parallel:latest
      options: --privileged  # This is required for Docker-in-Docker capabilities

    steps:
    - uses: actions/checkout@v2

    - name: Prepare and test DDPG
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        python TORCS_DDPG/train.py --device cpu --episodes 1
        python TORCS_DDPG/test.py --device cpu

    - name: Prepare and test NEAT
      run: |
        chmod +x TORCS_NEAT/CI_NEAT.sh
        TORCS_NEAT/CI_NEAT.sh

    - name: Run parallel NEAT
      run: |
        export HOST_PATH=$PWD
        python TORCS_NEAT/train_parallel.py --generations 1
